version: '3'
services:
  nginx:
    image: nginx:1.15
    container_name: blog_nginx
    working_dir: /usr/share/nginx/blog
    networks:
      - blog
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/blog
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  php_fpm:
    build: .
    container_name: blog_php_fpm
    working_dir: /usr/share/nginx/blog
    networks:
      - blog
    volumes:
      - ./:/usr/share/nginx/blog
  mysql:
    image: mysql:5.6.40
    container_name: blog_mysql
    networks:
      - blog
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
networks:
  blog:
    driver: bridge